spring.application.name=antiheros

spring.datasource.url=jdbc:postgresql://ep-wandering-grass-adz2ylwq-pooler.c-2.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_2pdjylqEgX6x&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=YOUR_PASSWORD
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE